---
title: "PFAS solubility"
author: "Anna Lindell"
date: "Oktober 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}
library(tidyverse)
library(readr)
library(ggh4x)
```




Read in data:
```{r eval = FALSE}
data <- read.table(file = "data/data.txt", 
                   sep = "\t", dec = ".", header = TRUE)
```


Plot samles:
```{r eval = FALSE}
pfda <- data %>% filter(compound == "PFDA")
pfna <- data %>% filter(compound == "PFNA")

ggplot(pfda, aes(x = group, y = response)) +
  geom_jitter(width = 0.1, size = 2, shape = 1) +
  facet_grid(cols = vars(concentration), rows = vars(matrix)) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        text = element_text(size=10),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size=10, angle = 90, vjust = 0.5, hjust = 1, color = "black"),
        axis.text.y = element_text(size=10, color = "black"),
        strip.background = element_rect(fill="white")) +
  labs(y = "Response") +
  ylim(0,1000000)
ggsave(file = "results/pfda.pdf",
       width = 12, height = 13, units = "cm")

ggplot(pfna, aes(x = group, y = response)) +
  geom_jitter(width = 0.1, size = 2, shape = 1) +
  facet_grid(cols = vars(concentration), rows = vars(matrix)) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        text = element_text(size=10),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size=10, angle = 90, vjust = 0.5, hjust = 1, color = "black"),
        axis.text.y = element_text(size=10, color = "black"),
        strip.background = element_rect(fill="white")) +
  labs(y = "Response") +
  ylim(0,1000000)
ggsave(file = "results/pfna.pdf",
       width = 5, height = 13, units = "cm")


```


